version: "3"

services:
  fulcrum:
    image: waltersouto/fulcrum:${TAG}@sha256:9e20ac0790c71a597a231bb0e1e321de1cd2e92efc4fb8db43833f1ac271d937
    restart: "no"
    ports:
      - "${HOST_PORT}:50002"
    volumes:
      - "${HOST_BTC_DIR}:/data/.bitcoin:ro"
      - "${HOST_DATA_DIR}:/data"
